### ISSUE TITLE
Fribidi link broken/other releases don't compile

### ISSUE THREAD

**Issue by pmdevita** [renpy/renios#3]
https://fribidi.org now redirects to the GitHub repo, https://github.com/fribidi/fribidi/, which breaks the link in the build-fribidi.sh script. The repo has a few older releases available but 0.19.2 is not one of them.

My two ideas to resolve this are to either use a different version of Fribidi or find another way for the script to obtain 0.19.2. 

The other releases of Fribidi available use different compile methods and are not "drop-in replacements". The older ones use automake and the newer ones use their autogen.sh script (which uses automake). I couldn't get automake to correctly work in the older releases and the newer releases using their autogen script give an error in the build. This solution may be problematic if there are API differences as well. 

0.19.2 can be obtained through the Wayback Machine here (http://web.archive.org/web/20120824092305/http://www.fribidi.org/) and everything works fine when it is dropped in the cache folder. It should probably be mirrored somewhere else though and not hotlinked to the Wayback Machine.

Thoughts?

**Comment by renpytom** [comment]
I'd suggest a reasonable place to get it from would be:

https://github.com/renpy/renpy-deps/tree/master/source

which is where I have the source for the PC platforms. (A very-long-term project would be to integrate Android, iOS, and PC builds into one repo.)

**Comment by pmdevita** [comment]
Ah I wish I had seen that before. Do you want me to submit a PR linking it to that repo?

**Comment by renpytom** [comment]
Yes, I think that would be a good thing.
